version: "3.9"

services:

  web:
    build: .
    container_name: chia_pipe
    # command: bash -c "bash 0.chia_pipe_shell.sh -c config_files/config_file_hg19.sh"
    command: sleep infinity
    
    volumes:
     - /home/agurova/ms/chiapipe_mod/gm19238:/Chiapipe_mod/gm19238

     - /home/agurova/data/hichip/yoruban/gm19238/ctcf/ctcf_merged:/Chiapipe_mod/fastq
     - /home/agurova/data/genomes/hg38:/Chiapipe_mod/reference
    #  - /home/agurova/ms/chiapipe_mod/config_files:/Chiapipe_mod/config_files
    #  - /home/agurova/ms/chiapipe_mod/util/scripts:/Chiapipe_mod/util/scripts
    #  - /home/agurova/ms/chiapipe_mod/shell_scripts:/Chiapipe_mod/shell_scripts