version: "3.9"

services:

  web:
    build: .
    command: bash -c "bash 0.chia_pipe_shell.sh -c config_file.sh && sleep 1000"
    volumes:
     - /mnt/c/MS/testing_chia_pipe/ChIA_PIPE_mod/LDK0004-ds:/Chiapipe_mod/LDK0004-ds
